# Generated by Django 5.2.7 on 2025-11-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltimateTeamApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='equipo',
        ),
        migrations.CreateModel(
            name='UsuarioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UltimateTeamApp.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UltimateTeamApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='propietarios', through='UltimateTeamApp.UsuarioEquipo', to='UltimateTeamApp.equipo'),
        ),
    ]
