# Generated by Django 5.2.7 on 2025-11-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltimateTeamApp', '0002_remove_usuario_equipo_usuarioequipo_usuario_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='equipos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='equipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='UltimateTeamApp.equipo'),
        ),
        migrations.DeleteModel(
            name='UsuarioEquipo',
        ),
    ]
