# Generated by Django 5.2.7 on 2025-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltimateTeamApp', '0003_remove_usuario_equipos_usuario_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='media',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Se calcula automáticamente al guardar'),
        ),
    ]
