# Generated by Django 5.2.7 on 2025-11-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltimateTeamApp', '0004_equipo_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='media',
        ),
        migrations.AddField(
            model_name='equipo',
            name='media_general',
            field=models.FloatField(default=0.0),
        ),
    ]
